import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import dynamic from "next/dynamic";
const NavbarServer = dynamic(() => import("./components/NavbarServer"), {
  ssr: true,
});
import { Toaster } from "react-hot-toast";
import { Providers } from "./providers";
const FooterServer = dynamic(() => import("./components/FooterServer"), {
  ssr: true,
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <Providers>
          {/* Server-driven Navbar with CMS data */}
          <NavbarServer />
          <main className="flex-1 flex flex-col">{children}</main>
          <FooterServer />
          <Toaster position="top-right" />
        </Providers>
      </body>
    </html>
  );
}
