import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import dynamic from "next/dynamic";
const NavbarServer = dynamic(() => import("./components/NavbarServer"), {
  ssr: true,
});
import { Toaster } from "react-hot-toast";
import { Providers } from "./providers";
const FooterServer = dynamic(() => import("./components/FooterServer"), {
  ssr: true,
});
import { NextIntlClientProvider, hasLocale } from "next-intl";
import { getMessages, setRequestLocale } from "next-intl/server";
import { notFound } from "next/navigation";
import { ReactNode } from "react";
import { routing } from "@/i18n/routing";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function generateStaticParams(): Promise<{ locale: string }[]> {
  return Promise.resolve(routing.locales.map((locale: string) => ({ locale })));
}

export default async function LocaleLayout({
  children,
  params,
}: {
  children: ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;

  // Validate locale
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  // Load messages for the locale
  let messages;
  try {
    messages = await getMessages({ locale });
  } catch (error) {
    console.error("Error loading messages:", error);
    notFound();
  }

  setRequestLocale(locale);

  return (
    <html lang={locale}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <Providers>
          <NextIntlClientProvider locale={locale} messages={messages}>
            {/* Server-driven Navbar with CMS data */}
            <NavbarServer />
            <main className="flex-1 flex flex-col">{children}</main>
            <FooterServer />
            <Toaster position="top-right" />
          </NextIntlClientProvider>
        </Providers>
      </body>
    </html>
  );
}
